# DELETE IN GITLUB 
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.15.191.2:3306/securitydb?characterEncoding=utf8
    username: zeal
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    user:
      name: zeal
      password: 123
      roles: admin, super, user
  thymeleaf:
    cache: false
  data:
    redis:
      host: 106.15.191.2
      port: 6379
      password: 1234
# mybatis 配置
mybatis:
  mapper-locations: classpath:com/zeal/securitytest/mapper/*.xml
  type-aliases-package: com.zeal.securitytest.entity
## 日志处理
#logging:
#  level:
#    com:
#      zeal:
server:
  servlet:
    session:
      timeout: 1
#        securitytest: debug
